remote_theme: pages-themes/cayman@v0.2.0
theme_color: '#000080'
timezone: TR
title: MOSARCH
subtitle: Recovery of Modular Software Architectures with Exact and Heuristic Clustering Methods
show_downloads: false
