remote_theme: chrisrhymes/bulma-clean-theme
theme_color: '#000080'
fixed_navbar: top
hide_footer: true
timezone: TR
title: MOSARCH
subtitle: Recovery of Modular Software Architectures with Exact and Heuristic Clustering Methods
show_downloads: false
